### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [alexstyl/Memento-Namedays#2]
With your app being open source, did you consider publishing the `.apk` along with the `releases/` – so folks without access to Playstore could grab it?

**Comment by alexstyl** [comment]
Good idea. From now on you can now find the `apk` of each version in the `Releases` section:
https://github.com/alexstyl/Memento-Namedays/releases/

**Comment by IzzySoft** [comment]
Thanks, Alex! Now your app can also be found [in my FDroid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/com.alexstyl.specialdates) and in the [special calendars](https://android.izzysoft.de/applists/category/named/office_calendar_general#group_57) section of my app listings :)
