### ISSUE TITLE
Latest APK throws error with aapt

### ISSUE THREAD

**Issue by IzzySoft** [alexstyl/Memento-Namedays#28]
#### Short Description

Running `aapt dump badging com.alexstyl.specialdates_3.7.apk` ends with `aapt` throwing the error `ERROR getting 'android:icon' attribute: attribute is not a string value`, exiting with code 1 – so tools using that (like fdroid-server while cataloging `.apk` files) assume an error and reject the `.apk`.

##### Steps to reproduce
Just run `aapt dump badging com.alexstyl.specialdates_3.7.apk`

##### Resulted in
`aapt` exiting with error code, fdroid-server rejecting the `.apk`, update not in catalog.

##### Expected Results
Well, take your guess: Clean exit, of course :)

##### Video/Screenshots
None. But:

##### Possible source of evil
I've applied a little Google-Fu, and found [getting " 'android:icon' attribute: attribute is not a string value” error while uploading an APK to the play store](http://stackoverflow.com/q/20800633/2533433) at StackOverflow. Assumed source at my end is indicated by [this answer](http://stackoverflow.com/a/37416988/2533433). You've got a "permanent loop definition" in `res/values/strings.xml`:

    <string name="localised_app_name">@string/app_name</string>
    …
    <string name="app_name">@string/localised_app_name</string>

This wasn't the case with v3.6 (which doesn't cause that error):

    <string name="localised_app_name">Memento Calendar</string>
    …
    <string name="app_name">@string/localised_app_name</string>

To confirm the issue, simply change back the `localized_app_name` definition to an "explicite string", and run `aapt` against the built package. If that fixes the issue, please replace the `.apk` attached to the v3.7 release.

Thanks in advance!

**Comment by alexstyl** [comment]
The APK is not going to be update for that specific version. A new release has already been pushed, with the issue resolved :)

https://github.com/alexstyl/Memento-Namedays/releases/tag/3.8

**Comment by IzzySoft** [comment]
Confirmed – thanks! And of course, in this case no need to update the "older APK" :) I've simply dropped that version from my repo (wasn't processed anyway because of the issue).

Again, thanks for the fast fix!
