### ISSUE TITLE
Contact does not appear when creating birthday

### ISSUE THREAD

**Issue by pchrysa** [alexstyl/Memento-Namedays#3]
**Short Description** 
1. My device has no contacts. 
2. Trying to add new birthday contacts through Memento.

**Steps to reproduce and Results** 
1. Create First contact (c1). 
Contact will not appear in the UI.
2. I create another one (c2). 
In the UI appears the previous contact (c1).
3. I create a third contact (c3) 
Again in the UI is painted the previous contact (c2).
4. I close the app. 
5. I reopen the app, contact c3 is completely missing (Although it exist on my phone contacts).
6. I create a new contact c4, the app works as intended and draws in the UI the c4 contact.

**Video**
What I just wrote, can be visible with the following gif:

![memento](https://cloud.githubusercontent.com/assets/1962633/18052398/daa2d00e-6e02-11e6-8dfc-757113471deb.gif)

**Comment by alexstyl** [comment]
Thank you for the report. The gif looks ace 💯

**Comment by alexstyl** [comment]
This issue is now fixed and will be available in the next release
