### ISSUE TITLE
Code duplication in Notifier

### ISSUE THREAD

**Issue by auricgoldfinger** [alexstyl/Memento-Namedays#33]
To provide a good and future-proof fallback for Event labels in notifications, I [duplicated the `getLabelFor()` code from `ContactEventView`](https://github.com/alexstyl/Memento-Namedays/pull/31#discussion_r77972857).

This duplication must be refactored so that the same code can be used in [`ContactEventView`](https://github.com/alexstyl/Memento-Namedays/blob/master/mobile/src/main/java/com/alexstyl/specialdates/upcoming/ui/ContactEventView.java#L58) as well as in `Notifier`.

**Comment by alexstyl** [comment]
Fixed in https://github.com/alexstyl/Memento-Namedays/pull/35
