### ISSUE TITLE
Select Date Dialog

### ISSUE THREAD

**Issue by cliffgr** [alexstyl/Memento-Namedays#7]
#### Short Description

Check/Uncheck checkbox on New Birthday date

##### Steps to reproduce

 1. Press Add button
 2. Press EditText Birthday
 3. Uncheck the Checkbox "Birthday Year"
 4. Press Finish
 5. Press EditText Birthday Again
 6. I see Birthday Year List but Checkbox is unchecked

##### Expected Results

Checkbox "Bithday Year" Checked

##### Video/Screenshots
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/4539769/18091925/1afde744-6ed3-11e6-839d-a920df679515.gif)

**Comment by alexstyl** [comment]
Good catch. Thanks for the report 👍

Some smaller resolution would be nicer next time

**Comment by alexstyl** [comment]
This issue is now fixed and will be available in the next release
